from __future__ import annotations

from typing import Protocol

from app.contracts.retrieval import (
    RetrievalChunkDescriptor,
    RetrievalDocumentDescriptor,
    RetrievalDocumentVersionDescriptor,
    RetrievalIngestionJobDescriptor,
    RetrievalIndexJobDescriptor,
    RetrievalSearchHit,
    RetrievalSourceDescriptor,
)


class RetrievalRepository(Protocol):
    def list_sources(self) -> list[RetrievalSourceDescriptor]: ...

    def list_source_ids(self) -> list[str]: ...

    def get_source(self, source_id: str) -> RetrievalSourceDescriptor | None: ...

    def list_documents_for_source(self, source_id: str) -> list[RetrievalDocumentDescriptor]: ...

    def get_document(self, document_id: str) -> RetrievalDocumentDescriptor | None: ...

    def list_chunks_for_document(self, document_id: str) -> list[RetrievalChunkDescriptor]: ...

    def list_document_versions(self) -> list[RetrievalDocumentVersionDescriptor]: ...

    def save_document_version(self, descriptor: RetrievalDocumentVersionDescriptor) -> None: ...

    def list_ingestion_jobs(self) -> list[RetrievalIngestionJobDescriptor]: ...

    def get_ingestion_job(self, job_id: str) -> RetrievalIngestionJobDescriptor | None: ...

    def save_ingestion_job(self, descriptor: RetrievalIngestionJobDescriptor) -> None: ...

    def search_indexed_chunks(
        self, *, query: str, source_ids: list[str], limit: int
    ) -> list[RetrievalSearchHit]: ...

    def list_index_jobs(self) -> list[RetrievalIndexJobDescriptor]: ...

    def get_index_job(self, job_id: str) -> RetrievalIndexJobDescriptor | None: ...

    def save_index_job(self, descriptor: RetrievalIndexJobDescriptor) -> None: ...

    def set_source_index_status(self, *, source_id: str, index_status: str) -> None: ...
