from __future__ import annotations

from typing import Protocol

from app.contracts.retrieval import (
    RetrievalChunkDescriptor,
    RetrievalDocumentDescriptor,
    RetrievalIndexedChunkDescriptor,
    RetrievalIndexJobEventDescriptor,
    RetrievalIndexJobDescriptor,
    RetrievalIndexJobRefreshDescriptor,
    RetrievalSourceDescriptor,
)


class RetrievalRepository(Protocol):
    def list_sources(self) -> list[RetrievalSourceDescriptor]: ...

    def list_source_ids(self) -> list[str]: ...

    def get_source(self, source_id: str) -> RetrievalSourceDescriptor | None: ...

    def list_documents_for_source(self, source_id: str) -> list[RetrievalDocumentDescriptor]: ...

    def get_document(self, document_id: str) -> RetrievalDocumentDescriptor | None: ...

    def list_chunks_for_document(self, document_id: str) -> list[RetrievalChunkDescriptor]: ...

    def list_searchable_indexed_chunks(
        self, source_ids: list[str]
    ) -> list[RetrievalIndexedChunkDescriptor]: ...

    def count_embedding_records(self) -> int: ...

    def count_embedding_records_for_source(self, source_id: str) -> int: ...

    def list_index_jobs(self) -> list[RetrievalIndexJobDescriptor]: ...

    def get_index_job(self, job_id: str) -> RetrievalIndexJobDescriptor | None: ...

    def list_index_job_events(self, job_id: str) -> list[RetrievalIndexJobEventDescriptor]: ...

    def refresh_index_job(self, job_id: str) -> RetrievalIndexJobRefreshDescriptor | None: ...
